// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package internal

import (
	"github.com/golang-friends/members/internal/application"
	"github.com/golang-friends/members/internal/config"
	"github.com/golang-friends/members/internal/githubservice"
)

// Injectors from wire.go:

func ProvideApplication(githubOauthToken githubservice.GitHubOAuthToken) *application.Application {
	configConfig := config.FromViper()
	gitHubService := githubservice.New(configConfig, githubOauthToken)
	applicationApplication := application.NewApplication(configConfig, gitHubService)
	return applicationApplication
}
